apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fast
spec:
  storageClassName: test-storageclass
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slow
spec:
  storageClassName: test-storageclass
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
