apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-server-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /shared/mysql-server-pv
    server: 211.183.3.100

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tomcat-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /shared/tomcat-pv
    server: 211.183.3.100


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /shared/nginx-pv
    server: 211.183.3.100
