apiVersion: v1
kind: Service
metadata:
  name: mysql-server
  labels:
    app: mysql-server
spec:
  ports:
    - port: 3306
  selector:
    app: mysql-server
    tier: db
  clusterIP: None

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-server
  labels:
    app: mysql-server
spec:
  selector:
    matchLabels:
      app: mysql-server
      tier: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-server
        tier: db
    spec:
      containers:
      - image: 61.254.18.30:5000/mysql:latest
        name: mysql
        envFrom:
        - secretRef:
            name: db-secret
        ports:
        - containerPort: 3306
          name: mysql-server
