---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: command-probe-pv
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /shared/command_probe
    server: 211.183.3.100

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: command-probe-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi



---
apiVersion: v1
kind : Pod
metadata:
  name: command-probe-test-pod
spec:
  containers:
  - name: nginx-container
    image: 61.254.18.30:5000/nginx
    volumeMounts:
    - name: command-probe-pv
      mountPath : /test
    readinessProbe:
      exec:
        command: ["cat","/test/test.txt"]
      initialDelaySeconds: 10
      periodSeconds: 3

  volumes:
  - name: command-probe-pv
    persistentVolumeClaim:
      claimName: command-probe-pvc

