apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-fail #
  labels:
    app: nginx-fail #
spec:
  containers:
  - name: nginx
    image: 61.254.18.30:5000/nginx
    # pod  


    readinessProbe:
      httpGet:
        path: /
        port: 80 #
      periodSeconds: 5
      initialDelaySeconds: 2
