apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app: redis

spec:
  containers:
  - name: redis-container
    image: 61.254.18.30:5000/redis
    readinessProbe:
      tcpSocket:
        port: 6379
      initialDelaySeconds: 5
      periodSeconds: 3
