apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-sample
spec:
  containers:
  - name: secret-container
    image: public.ecr.aws/docker/library/nginx:alpine
    envFrom:
    - secretRef:
        name: secret
