apiVersion: v1
kind: Service
metadata:
  name: svc-tom
spec:
  selector:
    app: tom
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  
---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: dep-tom

spec:
  replicas: 1
  selector:
    matchLabels:
      app: tom

  template:
    metadata:
      labels:
        app: tom

    spec:
      containers:
      - image: public.ecr.aws/docker/library/tomcat:10.1.40-jre11
        name: tom-con
