apiVersion: batch/v1
kind: Job
metadata:
  name: db-init
  namespace: board-app-eks
spec:
  template:
    spec:
      containers:
        - name: db-init
          image: mysql:8.0
          command:
            - sh
            - -c
            - |
              mysql -h $DB_HOST -u admin -p'$ADMIN_PASSWORD' -e "
              CREATE DATABASE IF NOT EXISTS boarddb CHARACTER SET utf8mb4;
              CREATE USER IF NOT EXISTS 'boarduser'@'%' IDENTIFIED BY 'boardpass';
              GRANT ALL PRIVILEGES ON boarddb.* TO 'boarduser'@'%';
              FLUSH PRIVILEGES;"
          env:
            - name: DB_HOST
              value: "<RDS 엔드포인트>"
            - name: ADMIN_PASSWORD
              value: "<RDS 마스터 패스워드>"
      restartPolicy: Never
