apiVersion: v1
kind: Secret
metadata:
  name: board-app-secret
  namespace: board-app-eks
type: Opaque
stringData:
  DB_HOST: "<RDS 엔드포인트>"
  DB_PORT: "3306"
  DB_USER: "boarduser"
  DB_PASSWORD: "boardpass"
  DB_NAME: "boarddb"

