apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
  namespace: default
data:
  default.conf: |
    server {
      listen      80;
      listen [::]:80;
      server_name localhost;
      
      location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
      }

      location /test {
      return 301 /;
      }

      error_page  500 502 503 504 /50x.html;
      location = /50x.html {
          root  /usr/share/nginx/html;
      }
    }

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-practice
  labels:
    app: nginx
spec:
  containers:
  - name: nginx-container
    image: 61.254.18.30:5000/nginx
    volumeMounts:
    - name: nginx-config-volume
      mountPath: /etc/nginx/conf.d/default.conf
      subPath: default.conf

    readinessProbe:
      httpGet:
        path: /test
        port: 80
      periodSeconds: 5
      initialDelaySeconds: 2

  volumes:
  - name: nginx-config-volume
    configMap:
      name: nginx-configmap
      items:
      - key: default.conf
        path: default.conf

