apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-mysql
spec:
  serviceName: "mysql"
  replicas: 2
  selector:
    matchLabels:
      app: statefulset-mysql
  template:
    metadata:
      labels:
        app: statefulset-mysql
    spec:
      containers:
      - name: statefulset-mysql
        image: 61.254.18.30:5000/mysql
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "test1234"

